<a href="https://colab.research.google.com/github/rushikeshnaik779/tfcerti/blob/main/17_21_shuffling_the_orders_of_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## shuffle the order of elements in a tensors

shuffle a tensor 

In [1]:
import tensorflow as tf 

In [2]:
not_shuffled = tf.constant([[10, 7], 
                            [3, 4],
                            [2, 5]])

not_shuffled.ndim

2

In [3]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [4]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [5]:
tf.random.set_seed(42) # global level seed 
tf.random.shuffle(not_shuffled, seed=42) # operational level seed 

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>


It looks like if we want our shuffled tensors to be in the same order, we've got to use the global level random seed and operational level random seed 

> If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.


# some other ways to get tensors 

In [6]:
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [7]:
tf.zeros(shape=(4, 5))

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

### Turn Numpy arrays into tensors 


The main difference betweeen numpy and tf tensors is that tensors can be run on a GPU Computing is faster  

In [8]:
# you can also numpy array into tensors 

import numpy as np 
nump_A = np.arange(1, 25, dtype=np.int32)
nump_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [9]:
A = tf.constant(nump_A, shape=(2, 6, 2))
A

<tf.Tensor: shape=(2, 6, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]], dtype=int32)>

# getting information from the tensors 

When dealing with tensors you probably want to be aware of the following attributes:
* Shape 
* Rank 
* Axis or Dimension 
* Size

In [10]:
# create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [11]:
rank_4_tensor[0][2][3]

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 0., 0., 0., 0.], dtype=float32)>

In [12]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [13]:
# Get Various Attribute of our tensor 
print("Data type of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank)", rank_4_tensor.ndim)
print("Shape of tensor", rank_4_tensor.shape)
print("Elments along the 0 axis", rank_4_tensor.shape[0])
print("ELements along the last axis", rank_4_tensor.shape[-1])
print("Total number of elements in our tensors:", tf.size(rank_4_tensor).numpy())
print("Total number of elements in our tensors without numpy:", tf.size(rank_4_tensor))

Data type of every element: <dtype: 'float32'>
Number of dimensions (rank) 4
Shape of tensor (2, 3, 4, 5)
Elments along the 0 axis 2
ELements along the last axis 5
Total number of elements in our tensors: 120
Total number of elements in our tensors without numpy: tf.Tensor(120, shape=(), dtype=int32)


## Indexing Tensors 

Tensors can be indexed just like a python list 

In [15]:
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [16]:
rank_4_tensor[:1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [17]:
rank_2_tensor = tf.constant([[10, 7], 
                             [2,4]])

rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [18]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 2],
        [ 4]]], dtype=int32)>

In [19]:
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 2],
        [ 4]]], dtype=int32)>

In [20]:
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 2,  4]]], dtype=int32)>

## Manipualting Tensors

**Basic Operation**

`+`, `-`, `\`, `*`

In [21]:
tensor = tf.constant([[10, 7], 
                      [3, 4]])

tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

### Multiplication `*`

In [22]:
tensor * 100

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1000,  700],
       [ 300,  400]], dtype=int32)>

In [23]:
# subtract 
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [26]:
# using tensorflow builtin functions 
tf.multiply(tensor, 20)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 140],
       [ 60,  80]], dtype=int32)>

In [27]:
tf.add(tensor, 12)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 19],
       [15, 16]], dtype=int32)>

In [28]:
tf.subtract(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [29]:
tf.divide(tensor, 2)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5. , 3.5],
       [1.5, 2. ]])>