<a href="https://colab.research.google.com/github/rushikeshnaik779/tfcerti/blob/main/tf14_certification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Fundamentals of tensor 

- More specifically 
    - intro to tensors 
    - info from tensors 
    - manipulating tensors 
    - tensors and nimpy
    - @tf.function ( a way to speed up you regular python functions ) 
    - using GPUs with tensorflow or TPUs 
    - Exercises to try for yourself! 

In [ ]:
# 

In [2]:
# import tensroflow 
import tensorflow as tf # tf is alias
print(tf.__version__)


2.5.0


In [11]:
# creating tesnors with tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [8]:
# check the number of dimension of a tensor (ndim stands for number of dimension )
scalar.ndim

0

In [9]:
# create a vector 
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [12]:
# check the dimension of our vector 
vector.ndim

1

In [13]:
# create a matrix 
matrix = tf.constant([[10, 7], 
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [14]:
matrix.ndim

2

In [16]:
# create another matrix 
another_matrix = tf.constant([[10., 7.],
                              [8., 9.],
                              [3., 2.]], dtype=tf.float16)
# specify the datatype by dtype parameter 

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 8.,  9.],
       [ 3.,  2.]], dtype=float16)>

In [17]:
# whats the number of dimension another matrix 
another_matrix.ndim

2

In [28]:
# let's create a tensor 

tensor = tf.constant([[[1,2,3], 
                       [4,5,6],
                       [7,8,9]],
                      [[10, 11, 12], 
                       [13, 14, 15], 
                       [16, 17, 18]], 
                      [[20, 21, 22], 
                      [23, 24, 25],
                      [26, 27, 28]]]
                      )
tensor

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[20, 21, 22],
        [23, 24, 25],
        [26, 27, 28]]], dtype=int32)>

In [29]:
tensor.ndim

3

What we've created so far : 

* scalar : single number
* vector : Number with direction (eg wind speed and direction)
* Matrix : a 2-d array of numbers 
* Tensor an n - dimensional array of numbers ( when n can be any number of 0 dimensional tensor is a scalar, 1-d tensor is a vector)